### ISSUE TITLE
Light turns on after connection lost

### ISSUE THREAD

**Issue by OnTarget600** [jeggleston1981/skyfandc#4]
Hello,

When the esp device becomes unavailable the light turns on. Is there a way to disable this behaviour.

**Comment by liouma** [comment]
This is how I corrected the problem:
`light:
  - id: skyfan_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false

fan:
  - id: skyfan
    platform: speed
    output: skyfan_speed
    direction_output: skyfan_direction
    name: ${fan_name}
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    speed_count: 6`

**Comment by liouma** [comment]
I will post my full code in case someone is interested. 
I fixed the lights on by default problem and there is also the color temperature management and fix for 24.06 esphome update. Also added some sensor to monitor the connection.
Labels are in french but you can easily translate it back to english

```
#Please edit name and IP (36)
substitutions:
  name: fan-bureau
  device_name: fan-bureau
  fan_name: Brasseur
  light_name: Plafonnier
  temp_name: Brasseur-Temp
  tmp117_name: "SkyFanDC TMP117"  
  skyfan_model: "SKY1203"
  light_color: "Temperature de la couleur"

#packages:
#  jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
#  name: ${device_name}
#  name_add_mac_suffix: true
  project:
    name: jimmy.easy_skyfandc
    version: "0.2"
  on_boot: #Setup temperature reading so you don't get a random reading come through at startup
    priority: -100
    then:
      - switch.turn_on: led
      - delay: 2s
      - switch.turn_off: led
api:
  encryption:
    key: oy7yLm88W7W3i5b35Dcw4eiDnyjbK2u0zwATzjkAhGc=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.20.51 #your_device_ip_here
    gateway: 192.168.20.1 #your_gateway_here
    subnet: 255.255.255.0
  ap:
    password: ""
    
packages:
#  skyfan.tuya_fan: github://jeggleston1981/skyfandc/tuya_fan.yaml  
#  skyfan.tuya_light: github://jeggleston1981/skyfandc/tuya_light.yaml  
  skyfan.sensor_ntc: github://jeggleston1981/skyfandc/sensor_ntc.yaml 
  skyfan.sensor_tmp117: github://jeggleston1981/skyfandc/sensor_tmp117.yaml 
  skyfan.sensor_power_fan: github://jeggleston1981/skyfandc/sensor_power_fan.yaml 
  skyfan.sensor_power_light: github://jeggleston1981/skyfandc/sensor_power_light.yaml 

esp8266:
  board: d1_mini
#web_server:
#  port: 80

#Dashboard import if you want to adopt the device on your esphome dashboard
dashboard_import:
  package_import_url: github://jeggleston1981/skyfandc/micro_skyfan2.yaml

# Logger not using the serial port as tuya needs it
logger:
  baud_rate: 0

# Version 0.2 has an i2c JST SH 4Pin Plug and uses the following pins
# Version 0.1 did use pin 4 as the power pin for the NTC
i2c:
  sda: 4
  scl: 5
  scan: true
ota:
 - platform: esphome

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

light:
  - id: skyfan_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false

fan:
  - id: skyfan
    platform: speed
    output: skyfan_speed
    direction_output: skyfan_direction
    name: ${fan_name}
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    speed_count: 6

output:
  # When the fan speed is changed by the fan entity in Home Assistant, update
  # the tuyamcu datapoints that control the fan motor.
  - id: skyfan_speed
    platform: template
    type: float
    write_action: 
      then:
        - if:
            condition:
              - switch.is_on: update_fan
            then:
              - switch.turn_off: update_fan            
            else:             
              - logger.log:
                  format: "skyfan_speed is %1f"
                  args: [ 'state' ]
              - select.set_index:
                  id: datapoint_direction
                  index: !lambda |-
                    return (id(skyfan).direction != FanDirection::FORWARD ? 1 : 0);              
              - if:
                  condition:
                    lambda: 'return state < 0.1 ;'
                  then:
                    - switch.turn_off: datapoint_onoff
                  else:
                    - switch.turn_on: datapoint_onoff                                     
                    - if:
                        condition:
                          lambda: 'return (state < 0.3);'
                        then:
                          - select.set_index:
                              id: datapoint_mode
                              index: 0
                          - number.set:
                              id: datapoint_speed
                              value: 1
                        else:
                          - if:
                              condition:
                                lambda: 'return (state < 0.4);'
                              then:
                                - select.set_index:
                                    id: datapoint_mode
                                    index: 1
                              else:                        
                                - select.set_index:
                                    id: datapoint_mode
                                    index: 0
                                - if:
                                    condition:
                                      lambda: 'return (state < 0.6);'
                                    then:
                                      - number.set:
                                          id: datapoint_speed
                                          value: 2
                                    else:                  
                                      - if:
                                          condition:
                                            lambda: 'return (state < 0.8);'
                                          then:
                                            - number.set:
                                                id: datapoint_speed
                                                value: 3
                                          else:                              
                                            - if:
                                                condition:
                                                  lambda: 'return (state < 0.9);'
                                                then:
                                                  - number.set:
                                                      id: datapoint_speed
                                                      value: 4
                                                else:                              
                                                  - number.set:
                                                      id: datapoint_speed
                                                      value: 5        

  - id: skyfan_direction
    platform: template
    type: binary
    write_action: []

tuya:
  id: tuyamcu
  on_datapoint_update:
    - sensor_datapoint: 1
      datapoint_type: bool
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 2
      datapoint_type: enum
      then:
        - switch.turn_on: update_fan 
    - sensor_datapoint: 3
      datapoint_type: int
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 8
      datapoint_type: enum
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 22
      datapoint_type: enum
      then: []

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    id: led
  # A datapoint has changed in tuyamcu. Update the fan entity in Home Assistant 
  # to be consistent with the new datapoint values.
  - id: update_fan
    platform: template
    optimistic: true
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition: 
              - switch.is_on: datapoint_onoff
            then:
              - if:
                  condition:
                    - lambda: 'return ( id(datapoint_mode).active_index() == 1 );'
                  then:
                    - logger.log: "update_fan ECO therefore set speed 2"
                    - fan.turn_on: 
                        id: skyfan
                        speed: '2'
                        direction: !lambda |-
                          bool val = ( id(datapoint_direction).active_index() != 0 );
                          return val ? FanDirection::REVERSE : FanDirection::FORWARD;
                  else:
                    - if:
                        condition:
                          - lambda: 'return ( id(datapoint_speed).state == 1 );'
                        then:
                          - logger.log: "update_fan Set speed 1"
                          - fan.turn_on: 
                              id: skyfan
                              speed: '1'
                              direction: !lambda |-
                                bool val = ( id(datapoint_direction).active_index() != 0 );
                                return val ? FanDirection::REVERSE : FanDirection::FORWARD;
                        else:
                          - logger.log: "update_fan Set speed plus 1"
                          - fan.turn_on: 
                              id: skyfan
                              speed: !lambda |-
                                return (id(datapoint_speed).state + 1);
                              direction: !lambda |-
                                bool val = ( id(datapoint_direction).active_index() != 0 );
                                return val ? FanDirection::REVERSE : FanDirection::FORWARD;
            else:
              - logger.log: "update_fan Turn off"
              - fan.turn_off: 
                  id: skyfan            

  - id: datapoint_onoff
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Switch
    switch_datapoint: 1
    internal: true

  - platform: restart
    name: Restart
    entity_category: diagnostic

select:
  - platform: "tuya"
    name: ${light_color}
    enum_datapoint: 19
    optimistic: true
    options:
      0: Froid
      1: Neutre
      2: Chaud

  - id: datapoint_mode
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Mode
    enum_datapoint: 2
    options:
      0: Normal
      1: Economie
      2: Sommeil
    disabled_by_default: false

  - id: datapoint_direction
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Direction
    enum_datapoint: 8
    options:
      0: FORWARD
      1: REVERSE
    internal: true

  - id: datapoint_timer
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Timer
    enum_datapoint: 22
    options:
      0: Désactivé
      1: 1 heure
      2: 2 heures
      3: 3 heures
      4: 4 heures
      5: 5 heures
      6: 6 heures
      7: 7 heures
      8: 8 heures
      9: 9 heures
      10: 10 heures
      11: 11 heures
      12: 12 heures
    disabled_by_default: false

number:

  - id: datapoint_speed
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Speed
    number_datapoint: 3
    min_value: 0
    max_value: 5
    step: 1
    internal: true

# Statut de l'ESP
binary_sensor:
  - platform: status
    name: "Statut" 
    entity_category: diagnostic

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Signal &"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: "diagnostic"
    device_class: ""
  - platform: uptime
    name: Uptime\config
    disabled_by_default: false
    force_update: false
    unit_of_measurement: s
    icon: mdi:timer-outline
    accuracy_decimals: 0
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic
    update_interval: 60s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
  - platform: version
    name: Version
    hide_timestamp: true
    disabled_by_default: false
    icon: mdi:new-box
    entity_category: diagnostic
```

**Comment by harrytheeskimo** [comment]
Thanks @liouma. This looks to have worked perfectly on my setup (SkyFanDC module direct from James). 

I used your light & fan entities and just extended the configurations from the micro_skyfan2.yaml package. 

The following is the full config in case helpful to anyone:

```yaml
substitutions:
  name: "bedroom-fan"
packages:
  jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: <encryption key>
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
ota:
  platform: esphome
light:
  - id: !extend skyfan_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
fan:
  - id: !extend skyfan
    platform: speed
    output: skyfan_speed
    direction_output: skyfan_direction
    name: ${fan_name}
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    speed_count: 6
```

**Comment by phatrickk** [comment]
> Thanks @liouma. This looks to have worked perfectly on my setup (SkyFanDC module direct from James).
> 
> I used your light & fan entities and just extended the configurations from the micro_skyfan2.yaml package.
> 
> The following is the full config in case helpful to anyone:
> 
> ```yaml
> substitutions:
>   name: "bedroom-fan"
> packages:
>   jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
> esphome:
>   name: ${name}
>   name_add_mac_suffix: false
> api:
>   encryption:
>     key: <encryption key>
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
>   domain: .lan
> ota:
>   platform: esphome
> light:
>   - id: !extend skyfan_light
>     platform: tuya
>     name: ${light_name}
>     switch_datapoint: 15
>     dimmer_datapoint: 16
>     min_value: 0
>     max_value: 5
>     restore_mode: RESTORE_DEFAULT_OFF
>     disabled_by_default: false
> fan:
>   - id: !extend skyfan
>     platform: speed
>     output: skyfan_speed
>     direction_output: skyfan_direction
>     name: ${fan_name}
>     restore_mode: RESTORE_DEFAULT_OFF
>     disabled_by_default: false
>     speed_count: 6
> ```

Hi, I've just picked up one of these esphome USB modules and it arrived the other day. I've installed it and pulled the device into home assistant and all but the light controls seems to work great. I'm really keen to be able set colour temp of the light via HASS, so I'm wondering if you might be generous enough to talk me through the exact process to get this config up and working?

So far what I've done is:

Install ESPhome addon, adopt the skyfan device that was already there, updated the 'easy-skyfandc-xxxxx.yaml with the code above (keeping of course the relevant wifi and encryption info relevant to me), saved.

Hit install, chosen wirelessly. At which point it runs through an install process seemingly succesfully and then it "Starting log output". A wall of purple text running through details of the device comes through, with the only thing that appears to be out of place is the "[17:43:45][E][tmp117:046]: Communication with TMP117 failed!". Assuming that's nothing to worry about because I think the board was designed for an external temp sensor which I don't need. It then continues to log states of the sensors indefinitely as far as I can tell.

Unfortunately I don't seem to have any additional entities show up for colour temp or anything else. I'm assuming I need to do something with liouma's longer section of code, but I'm not sure exactly what or where to do it.

Thanks

**Comment by harrytheeskimo** [comment]
From a quick glance it looks like there are some colour temperature properties added to https://github.com/jeggleston1981/skyfandc/blob/main/tuya_light.yaml already but they're commented out - possibly not yet confirmed working.

I'd suggest trying the **!extend skyfan_light** above and experimenting with the additional properties commented out in tuya_light.yaml, as well as the commented 'select' entities there which look to be used for CCT switching.

My configuration is the same as yours, but I've no desire to use anything except Warm White for this bedroom fan so never noticed the missing CCT control. 

The TMP117 refers to an optional temperature sensor btw, it can be added for an external temp reading (per the note [here](https://www.egglec.com.au/post/skyfan-dc-guide-for-home-assistant)).

**Comment by Archy54** [comment]
What's the api encryption key? Is that a specific never change number or unique to each device?

**Comment by harrytheeskimo** [comment]
> What's the api encryption key? Is that a specific never change number or unique to each device? 

Yep it's unique to each device, and generally created for you by esphome when you create a new device.

https://esphome.io/components/api.html

**Comment by Archy54** [comment]
Will this code for skyfan2 work on the non i2c (last years version) with colour temp? 

https://pastebin.com/HNEaweMA That's what's on there atm

**Comment by cjhowell** [comment]
Came here as I am experiencing this issue. Bought the module from James in 2023 and have used it as it came as I was new to HA and didn't understand how to flash or update the YAML.

Still learning but have at least worked out I needed to install ESPHome Builder. With that, I can see my current YAML is:

```
substitutions:
  name: easy-skyfandc-f0e167
packages:
  jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: redacted


wifi:
  ssid: wifi_ssid
  password: wifi_password
```
Am I right in understanding that I need to paste the YAML from either @liouma or @harrytheeskimo above but retain the 'easy-skyfandc-f0e167' and api key which I've redacted.

If I paste the YAML with the correct name and api into ESPHome Builder I can then update the module and the light issue should go away?

**Comment by phatrickk** [comment]
Yep. After your wifi section, you would add the code that fixes the issue you're having. Can't work out if it's turning on after the connection lost or something else. I haven't needed to fix that issue, and haven't currently got it in my code block. I just wanted to control the colour of the light, so I have the following code block after my wifi section. Thanks to those above for posting it originally.

EDIT: After the millionth edit trying to get the code block working correctly, it looks like I did grab the code for not restoring defaults for the fan and light after power out.

```
substitutions:
  name: family-room-fan
packages:
  jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: XXX
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.107
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
ota:
  platform: esphome
light:
  - id: !extend skyfan_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
fan:
  - id: !extend skyfan
    platform: speed
    output: skyfan_speed
    direction_output: skyfan_direction
    name: ${fan_name}
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    speed_count: 6
select:
  - platform: "tuya"
    name: ${light_color}
    enum_datapoint: 19
    optimistic: true
    options:
      0: Cold
      1: Neutral
      2: Warm
```
