### ISSUE TITLE
Deta Smart Fan Switch (AC to DC) EspHome Wall Controller works with SkyFan DC // yaml included.

### ISSUE THREAD

**Issue by EvoSems** [jeggleston1981/skyfandc#7]
Hey Guys, I have my old [https://devices.esphome.io/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch](url) Deta Controller I was using with my old AC fan working perfectly with this sky fan usb module, everything auto reflects in home assistant also. you can get the controller at Bunnings. 

Edit the yaml before you flash with your own details!!

no more seperate remote for the non tech wife!

```
substitutions:
  device_name: master-bed-fan-and-lights
  fan_name: "Sky Fan DC"

esphome:
  name: ${device_name}
  friendly_name: "Master Bed Fan + Lights"

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret wifi_password

logger:
  baud_rate: 0
  logs:
    component: ERROR

captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO16
    id: button1
    on_press:
      then:
        - light.toggle: light1
        - script.execute: blink_gpio3

  - platform: gpio
    pin: GPIO00
    id: button2
    on_press:
      then:
        - homeassistant.service:
            service: fan.toggle
            data:
              entity_id: fan.skyfandc_sky_fan_dc
        - script.execute: blink_gpio3

  - platform: gpio
    pin: GPIO05
    id: button3
    on_press:
      then:
        - homeassistant.service:
            service: fan.set_percentage
            data_template:
              entity_id: fan.skyfandc_sky_fan_dc
              percentage: >
                {% set speeds = [17, 33, 50, 67, 83, 100] %}
                {% set current = state_attr('fan.skyfandc_sky_fan_dc', 'percentage') | int %}
                {{ speeds[(speeds.index(current) + 1) % speeds | length] }}
        - script.execute: blink_gpio3

script:
  - id: blink_gpio3
    mode: restart
    then:
      - output.turn_on: gpio3_led
      - delay: 200ms
      - output.turn_off: gpio3_led

light:
  - platform: binary
    id: light1
    name: "Light"
    output: relay1_light

switch:
  - platform: restart
    name: Reboot

  - platform: gpio
    id: relay_fan_1
    name: "Relay Fan 1"
    pin: GPIO13
    restore_mode: ALWAYS_ON
    internal: true

  - platform: gpio
    id: relay_fan_2
    name: "Relay Fan 2"
    pin: GPIO04
    restore_mode: ALWAYS_ON
    internal: true

  - platform: gpio
    id: relay_fan_3
    name: "Relay Fan 3"
    pin: GPIO15
    restore_mode: ALWAYS_ON
    internal: true

output:
  - platform: gpio
    pin: GPIO3
    id: gpio3_led
    inverted: True

  - platform: gpio
    pin: GPIO14
    id: relay1_light
```
